version: '3.8'

services:
  mongo:
    image: mongo:6.0
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  app:
    build: .
    container_name: sber_api
    ports:
      - "8000:8000"
    environment:
      MONGO_URI: mongodb://root:example@mongo:27017/
      MONGO_DB: sber_db
    depends_on:
      - mongo

volumes:
  mongo_data: